### ISSUE TITLE
Kerahasiaan data

### ISSUE THREAD

**Issue by taufn** [ghuniyu/sekitarkita-backend#10]
Halo,

Saya punya sedikit _concern_, sama seperti _concern_ saya terhadap aplikasi TraceTogether di SG. Bagaimana cara data yang terkumpul dikelola? Apakah ada mekanisme otorisasi bahwa data hanya bisa diakses oleh orang yang sudah mendapat kewenangan? Karena menurut saya data yang dikumpulkan sangat personal, dan implikasinya bisa luas jika disalahgunakan.

FYI, saya tidak bermaksud negatif. Justru aplikasi ini menurut saya sangat baik tujuannya. Hanya saja saya ingin memastikan tidak ada kebocoran data.

Best,
Taufan

**Comment by WillyRL** [comment]
Halo Selamat Siang,

Data yang dikumpulkan dari aplikasi ini hanya Bluetooth Address, yang sifatnya sama dengan MAC Address, tidak ada data pribadi ataupun data lainnya.

Sejauh ini, bluetooth address hanya sebagai _unique identification_ untuk masing-masing perangkat :) 


Terimakasih telah berkomentar
