### ISSUE TITLE
Ability to search or filter mapping member by mac address

### ISSUE THREAD

**Issue by ginanjarfm** [ghuniyu/sekitarkita-backend#33]
Capability for user to search at mapping member pages by mac address.

Also please fix this hidden legend. 👻 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1422134/77709625-4fd5a800-6ffe-11ea-9735-e459cdb9e835.png">

**Comment by ghuniyu** [comment]
will update it soon...
